branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: Wordlist
  branch: null
  default_platform: Go 1.13.2
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  workspace_type: Application
