branch-defaults:
  master:
    environment: wordlist-dev
environment-defaults:
  wordlist-dev:
    branch: null
    repository: null
global:
  application_name: wordlist
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Go 1 running on
    64bit Amazon Linux/2.14.1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
